backend:
  name: github
  repo: electricvino/jv-info
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

collections:
  - name: "post"
    label: "Post"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

